### ISSUE TITLE
Please add me to the organization so I can see private repos

### ISSUE THREAD

**Issue by ryandeussing** [ScriptEdcurriculum/curriculum2015#20]
Either I removed myself by mistake, or I was removed by accident. Thanks

**Comment by ScriptEdNYC** [comment]
Just sent you an invite.. let me know if you have any trouble accessing!

On Thu, Jan 7, 2016 at 11:30 AM, Ryan Deussing notifications@github.com
wrote:

> Either I removed myself by mistake, or I was removed by accident. Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ScriptEdcurriculum/curriculum2015/issues/20.

## 

Rebecca Novak | Director of Programs and Community Affairs
ScriptEd, Inc.
85 Broad Street, 17th Floor
New York, NY 10004
(917) 565 - 6477
becca@scripted.org | scripted.org
ScriptEd on Twitter: @scriptedorg http://twitter.com/scriptedorg | Me on
Twitter: @beckano http://twitter.com/beckano

Interested in getting involved? Fill out a volunteer application here:
bit.ly/ScriptEdVolunteer

To donate: http://scripted.org/#donate
